name: Manual Full Archive Execute-Store-Generate HTML
on:
  workflow_dispatch:

jobs:
  GenerateHTML:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/notebook-ci-unified.yml@v1
   with:
      execution-mode: 'on-demand'
      trigger-event: 'all'
      python-version: ${{ vars.PYTHON_VERSION || '3.12' }}
      enable-html-build: true
   permissions:
     contents: write
